[package]
name = "tuple_set"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tupleops = "0.1.1"
moddef = "0.2.2"
cond = {path = "../cond"}